name: build-master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    container: tarscloud/base-compiler
    runs-on: ubuntu-20.04
    steps:
      - name: env
        run: env
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: docker.tarsyun.com
          username: ${{ secrets.name }}
          password: ${{ secrets.pass }}
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.MY_TOKEN }}
      - name: Set up QEMU
        run: |
          docker run --rm --privileged tonistiigi/binfmt:latest --install all
      - name: Create Build
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker buildx create --name mybuild --use
          docker buildx inspect --bootstrap --builder mybuild
      - name: Buildx
        run: |
          exec-buildx-cloud.sh cpp yaml/values.yaml ${{ steps.get_version.outputs.VERSION }} Dockerfile
